name: canvas-universal-env
channels:
  - conda-forge
  - anaconda
  - anaconda-fusion
  - defaults
dependencies:
  - python>=3.7.0
  - python-dotenv
  - reportlab # only used in quiz-reports
  - termcolor
  - requests
  - jupyter
  - pandas
  - pip
  - pip:
      - canvasapi>=2.0.0
      - beautifulsoup4 # only used in syllabus-scraper
      - pick
      - art # only used in setup-test
